server:
  port: ${SERVER_PORT:20020}
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 1m
    max-connections: 8192
    accept-count: 100
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100

management:
  server:
    port: ${MANAGEMENT_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: account-service
  config:
    import:
      - logging.yml
      - monitoring.yml
      - redis.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}
    endpoints:
      authorization: https://accounts.google.com/o/oauth2/v2/auth
      token: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v3/userinfo
    scope:
      - profile
      - email
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    endpoints:
      token: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
    redirect-uri: ${OAUTH_NAVER_REDIRECT_URI}
    endpoints:
      token: https://nid.naver.com/oauth2.0/token
      user-info: https://openapi.naver.com/v1/nid/me

jwt:
  token-exp-seconds:
    access: 3600
    refresh: 86400
    temporary: 600
  token-claims:
    issuer: codecrew
    audience: codecrew-account
  secret: ${JWT_SECRET}

