server:
  port: ${SERVER_PORT}
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 1m
    max-connections: 8192
    accept-count: 100
    keep-alive-timeout: 60s
    max-keep-alive-requests: 100

management:
  server:
    port: ${MANAGEMENT_PORT}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: ${APPLICATION_NAME}
  config:
    import:
      - logging.yml
      - monitoring.yml
      - redis.yml
      - kafka.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  kafka:
    consumer:
      group-id: world-service-group

app:
  kafka:
    topics:
      member-events: outbox.member

  agones:
    namespace: ${AGONES_NAMESPACE}
    fleet-name: ${AGONES_FLEET_NAME}
    ingress-domain: ${AGONES_INGRESS_DOMAIN}
    use-ingress: ${AGONES_USE_INGRESS:false}
  world:
    cache:
      enter-token: ${WORLD_CACHE_ENTER_TOKEN}
      server-heartbeat: ${WORLD_CACHE_SERVER_HEARTBEAT}

