[versions]
java = "25"
springBoot = "4.0.0"
springBootAop = "4.0.0-M2"
springDependencyManagement = "1.1.7"
springCloudDependenciesVersion = "2025.1.0"
springdocOpenapiStarterWebmvcUi = "3.0.0"
springFramework = "7.0.2"
errorpronePlugin = "4.1.0"
lombok = "1.18.42"
errorprone = "2.26.1"
nullaway = "0.11.3"
testcontainers = "1.19.7"
jakarta-persistence = "3.2.0"
jackson-bom = "3.0-rc5"
classgraphVersion = "4.8.184"
logstashLogbackEncoder = "9.0"
p6spySpringBootStarter = "2.0.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }

[libraries]
spring-framework-web = { module = "org.springframework:spring-web" }
jackson-annotation = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-bom" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
io-github-classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraphVersion" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "springBootAop" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapiStarterWebmvcUi"}
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
p6spy-spring-boot-starter = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version.ref = "p6spySpringBootStarter" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-data-redisson = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-data-redis-reactive = { module = "org.springframework.boot:spring-boot-starter-data-redis-reactive"}
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-webflux = {module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka", version.ref = "springBoot"}
flyway-mysql = { module = "org.flywaydb:flyway-mysql" }
mysql-connector = { module = "com.mysql:mysql-connector-j" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
org-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashLogbackEncoder" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
spring-boot-micrometer-tracing = { module = "org.springframework.boot:spring-boot-micrometer-tracing" }
spring-boot-micrometer-tracing-brave = { module = "org.springframework.boot:spring-boot-micrometer-tracing-brave" }
micrometer-tracing-bridge-brave = { module = "io.micrometer:micrometer-tracing-bridge-brave" }

netty-resolver-dns-macos = { module = "io.netty:netty-resolver-dns-native-macos" }

spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "springFramework" }
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "springCloudDependenciesVersion" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spring-dependency-management-gradle-plugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "springDependencyManagement" }
errorprone-gradle-plugin = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorpronePlugin" }

[bundles]
spring-framework-web = [
    "spring-framework-web"
]

spring-boot-web = [
    "spring-boot-starter-web",
    "spring-boot-starter-validation",
    "springdoc-openapi-starter-webmvc-ui"
]

spring-boot-data-jpa = [
    "spring-boot-starter-data-jpa",
    "p6spy-spring-boot-starter"
]

spring-boot-data-redis = [
    "spring-boot-starter-data-redis",
    "spring-boot-starter-data-redisson",
    "spring-boot-starter-data-redis-reactive"
]

spring-boot-logging = [
    "spring-boot-starter-logging",
    "logstash-logback-encoder"
]

spring-boot-monitoring = [
    "spring-boot-starter-actuator",
    "micrometer-prometheus",
    "spring-boot-micrometer-tracing",
    "spring-boot-micrometer-tracing-brave",
    "micrometer-tracing-bridge-brave"
]

spring-boot-test = [
    "spring-boot-starter-test",
    "testcontainers-junit",
    "org-junit-jupiter"
]

mysql-datasource = [
    "mysql-connector"
]

jackson = [
    "jackson-annotation",
    "jackson-databind",
    "jackson-datatype-jsr310"
]