server:
  port: ${SERVER_PORT}
  shutdown: graceful

management:
  server:
    port: ${MANAGEMENT_PORT}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: ${APPLICATION_NAME}
  config:
    import:
      - logging.yml
      - monitoring.yml
      - redis.yml
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      max-acquire-time: 30m
      max-life-time: 60m
      validation-query: "SELECT 1"

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}




